#!/usr/bin/env python3
"""
10. Pre/Post Context-Buffered Chunking
Book: Chapter 6, Chunking Strategies -- section 3.9

WHAT THIS SHOWS: Give each chunk a short summary of what came immediately
before and after it -- no more than 50 tokens each, generated by a model at
index time.

This is the first strategy in the book that spends an LLM call per chunk. That
changes its economics completely: examples 02-09 reindex for free, this one
reindexes for money. The question it has to answer is whether a paragraph of
borrowed context is worth more than the same tokens spent on a larger chunk.

HOW THIS SCRIPT PROCEEDS
    1. Start from example 05's chunks
    2. Ask a model to summarise each one   one API call per chunk
    3. Enforce the 50-token cap in CODE    <-- not in the prompt
    4. Attach each summary to its NEIGHBOURS  <-- THE TECHNIQUE
    5. Embed chunk + borrowed context

Step 4 is the inversion worth watching: a chunk's summary is never attached to
itself, only to the chunks either side of it.


WHAT CHANGED SINCE EXAMPLE 09
    Example 09 borrowed context from the document's structure, for free. This
    borrows it from a model, for money -- one call per chunk, paid again on
    every reindex. It is the first strategy in the book whose cost scales with
    corpus size rather than being a one-off.


REQUIRES: OPENAI_API_KEY (falls back to showing the prompt)
RUN: python examples/10_chunk_context_buffered.py [--limit 20]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from importlib import import_module

from ragkit import config, display, llm, tokens
from ragkit.corpus import Book, Chunk, load_book

STRATEGY = "context_buffered"

# The book's cap. It is a budget, not a target: a summary that runs long stops
# being context and starts being a second chunk competing with the first.
MAX_SUMMARY_TOKENS = 50

SYSTEM = (
    "You summarise passages of fiction for a retrieval index. "
    "You write one sentence, under 40 words, in plain declarative prose. "
    "You never add commentary, and you never mention that you are summarising."
)

PROMPT = """Summarise the following passage in one sentence of at most 40 words.
The summary will be attached to the *neighbouring* passage as context, so
prioritise who is present, where they are, and what just happened.

PASSAGE:
{passage}"""


def summarise(passage: str) -> str:
    """One neighbour summary. Cached on disk by ragkit.llm."""
    text = llm.complete(
        PROMPT.format(passage=passage),
        system=SYSTEM,
        temperature=0.0,
        max_tokens=100,
        purpose="neighbour summaries for context-buffered chunking",
    )
    # ---- THE KEY DEFENCE -------------------------------------------
    # The budget is enforced here, in code, not by the "at most 40 words"
    # instruction in the prompt. Models overrun word limits routinely, and
    # an unbounded summary stops being context and becomes a second chunk
    # competing with the first for influence over one vector.
    units = tokens.encode(text)
    if len(units) > tokens.units_for_tokens(MAX_SUMMARY_TOKENS):
        text = tokens.decode(units[: tokens.units_for_tokens(MAX_SUMMARY_TOKENS)]) + "..."
    return text.strip()


def chunk_context_buffered(book: Book, limit: int | None = None) -> list[Chunk]:
    """Wrap each chunk in summaries of its neighbours.

    We build on example 05's heading chunks so the only new variable is the
    buffering. Each chunk's embedded string becomes:

        [summary of previous chunk] + [the chunk] + [summary of next chunk]

    The chunk body itself is untouched -- as in example 09, what changes is
    ``retrieval_text``.
    """
    base = import_module("05_chunk_heading").chunk_by_heading(book)
    if limit:
        base = base[:limit]

    # Neighbours are taken within a section. A summary of the last chunk of
    # one story attached to the first chunk of the next would be actively
    # misleading, which is the sort of bug that only shows up as slightly
    # worse retrieval three weeks later.
    summaries: list[str] = []
    for position, chunk in enumerate(base):
        print(f"    summarising {position + 1}/{len(base)}", end="\r", flush=True)
        summaries.append(summarise(chunk.text))
    print(" " * 40, end="\r")
    print()

    out: list[Chunk] = []
    for position, chunk in enumerate(base):
        same_section = lambda other: (
            other.story == chunk.story and other.section == chunk.section
        )
        before = (
            summaries[position - 1]
            if position > 0 and same_section(base[position - 1])
            else ""
        )
        after = (
            summaries[position + 1]
            if position + 1 < len(base) and same_section(base[position + 1])
            else ""
        )

        # ---- THE TECHNIQUE -----------------------------------------
        # Assemble: [summary of PREVIOUS] + this chunk + [summary of NEXT].
        # The markers are visible on purpose, so a model reading this
        # string can never mistake borrowed context for source text.
        parts = []
        if before:
            parts.append(f"[Previously: {before}]")
        parts.append(chunk.text)
        if after:
            parts.append(f"[Next: {after}]")

        chunk.strategy = STRATEGY
        chunk.retrieval_text = "\n\n".join(parts)
        chunk.meta["pre_summary"] = before
        chunk.meta["post_summary"] = after
        chunk.meta["buffer_tokens"] = tokens.count_tokens(before + after)
        out.append(chunk)

    return out


def explain_without_key(book: Book) -> None:
    """Show the mechanics for a reader with no API key."""
    base = import_module("05_chunk_heading").chunk_by_heading(book)
    sample = base[4]

    display.para(
        "Without a key this example cannot generate summaries. The prompt is "
        "most of the technique, though, so here is exactly what would be sent "
        "for one real chunk of the corpus, and what would be done with the "
        "reply."
    )
    display.prompt_block("SYSTEM", SYSTEM)
    display.prompt_block("USER", PROMPT.format(passage=display.truncate(sample.text, 600)))
    display.illustrative(
        "In their Baker Street rooms, Holmes tells Watson that he sees but does",
        "not observe, citing the seventeen stairs Watson has climbed for years",
        "without ever counting.",
    )
    print()
    display.para(
        "That sentence would then be attached to the chunks either side of "
        "this one, wrapped in [Previously: ...] and [Next: ...] markers, and "
        "embedded with them. The chunk's own stored text would be unchanged."
    )
    print()
    display.kv("cost", f"one call per chunk -- {len(base):,} calls for this corpus")
    display.kv("summary budget", f"{MAX_SUMMARY_TOKENS} tokens each, truncated if over")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--limit",
        type=int,
        default=20,
        help="how many chunks to buffer (each costs one API call)",
    )
    args = parser.parse_args()

    display.banner(
        "10. Pre/Post Context-Buffered Chunking",
        "Chapter 6, Chunking Strategies -- section 3.9",
        "Attach a model-written summary of the previous and next chunk, so a "
        "passage retrieves with the situation it sits in.",
    )

    book = load_book()

    if not llm.available():
        print(f"  No LLM configured: {llm.why_unavailable()}\n")
        explain_without_key(book)
        display.notice(
            "This is the first strategy in the book that cannot be run for "
            "free. Every chunk costs a call at index time, and every reindex "
            "costs them again.",
            "The summaries are cached on disk by ragkit/llm.py, so re-running "
            "these examples while reading does not re-spend.",
            "Everything in examples 02-09 produces boundaries from text alone. "
            "Before paying for this one, example 15 is worth reading -- it "
            "measures whether the free strategies were already good enough on "
            "this corpus.",
        )
        return 0

    if llm.STUB:
        display.stub_warning()
    else:
        print(f"  model: {config.OPENAI_CHAT_MODEL}")
        print(f"  cached responses on disk: {llm.cached_count():,}")
    print()

    chunks = chunk_context_buffered(book, args.limit)

    display.kv("chunks buffered", f"{len(chunks):,}")
    overhead = sum(c.meta["buffer_tokens"] for c in chunks) / len(chunks)
    display.kv("buffer cost", f"{overhead:.0f} tokens per chunk")

    display.heading("One chunk, before and after buffering")
    sample = next(c for c in chunks if c.meta["pre_summary"] and c.meta["post_summary"])
    print("  STORED TEXT (unchanged):")
    display.preview(sample.text, limit=200)
    print("\n  EMBEDDED TEXT:")
    for line in sample.embed_text.split("\n\n"):
        display.preview(line, limit=200)

    display.sample_chunks(chunks, n=4, start=0, count_tokens=tokens.count_tokens)

    display.notice(
        f"Each chunk now carries about {overhead:.0f} tokens of borrowed "
        "context in its embedding, written by a model at index time.",
        "The summaries live in the embedded string only. The model still reads "
        "the clean passage, so a summary can never be quoted back as though it "
        "were the source.",
        "Neighbours are taken within a section. Crossing a story boundary here "
        "would attach one adventure's context to another's opening and quietly "
        "degrade both.",
        "Summary length is enforced in code, not asked for in the prompt. "
        "Models overrun word limits, and an unbounded summary turns into a "
        "second chunk competing with the first.",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
